- hosts: localhost
  vars:
    homebrew_upgrade_all_packages: yes
    mas_upgrade_all_apps: yes

    homebrew_taps:
      - homebrew/core
      - homebrew/cask-fonts

    homebrew_installed_packages:
      - ack
      - asdf
      - awscli
      - archey
      - fzf
      - git
      - gnupg
      - htop
      - jq
      - nmap
      - nvim
      - pinentry-mac
      - python3
      - speedtest-cli
      - ssh-copy-id
      - tmux
      - tree
      - wget
      - zsh

    homebrew_cask_apps:
      - alfred
      - brave-browser
      - docker
      - fantastical
      - font-fira-code-nerd-font
      - timche-gmail-desktop
      - google-chrome
      - handbrake
      - iterm2
      - keybase
      - microsoft-edge
      - onedrive
      - parallels
      - postman
      - slack
      - spotify
      - telegram
      - the-unarchiver
      - tunnelblick
      - visual-studio-code
      - zerotier-one

    mas_installed_apps:
      - { id: 441258766, name: "Magnet" }
      - { id: 1333542190, name: "1Password 7 - Password Manager" }
      - { id: 937984704, name: "Amphetamine" }
      - { id: 1451685025, name: "Wireguard" }

  roles:
    - geerlingguy.homebrew
    - geerlingguy.mas

  tasks: 
    - name: Set up zsh syntax highlighting
      git:
          dest: "{{ lookup('env','HOME') }}/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting"
          repo: "https://github.com/zsh-users/zsh-syntax-highlighting.git"
          force: yes
    - name: Set up zsh autosuggestions
      git:
          dest: "{{ lookup('env','HOME') }}/.oh-my-zsh/custom/plugins/zsh-autosuggestions"
          repo: "https://github.com/zsh-users/zsh-autosuggestions.git"
          force: yes